export const SCROLLED_IN_AFFECTED_AMOUNT = 6
export const SCROLLED_IN_INFLUENCED_AMOUNT = 3
export const SCROLL_BASE_SCALE_Y = 1
export const SCROLL_LAMBDA = 100 //LAMBDA AFFECTS HOW SUDDEN THE ANIMATION WILLL GO

export const ITEM_PRESELECTED_GRAYSCALE_AMOUNT = .5
export const ITEM_SELECTED_GAP_TIME = 6
export const ITEM_BASE_SCALE_Y = 2
export const ITEM_SELECTED_GAP_X = 1
export const ITEM_UNSELECT_DELAY = 3
export const ITEM_SELECT_COLOR_DELAY = .75


export const SCROLL_CLICKED_SCALE_Y = 2
export const SCROLL_CLICKED_SCALE_X = 4.25
export const SCROLL_UNFOCUSED_GAP = 2
export const SCROLL_FOCUS_DELTA_MULTIPLIER = 1
export const SCROLL_FOCUSED_COLOR = 'white'
export const SCROLL_UNFOCUSED_COLOR = '#aaa'
export const SCROLL_GRAYSCALE = .85